name: sample_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Icons & Images
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  # Service locator
  get_it: 7.2.0
  # Functional programming thingies
  dartz: ^0.10.0
  # Value equality
  equatable: ^2.0.3
  # Local storage
  flutter_secure_storage: ^5.0.2
  # API requests
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  # State management
  provider: ^6.0.3
  # Connection check
  internet_connection_checker: ^0.0.1+3
  # Loading
  flutter_spinkit: ^5.1.0
  modal_progress_hud_nsn: ^0.2.1
  # Date time formatting
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/